import Head from 'next/head'
import Image from 'next/image'
import { Open_Sans } from 'next/font/google'
import { ModeSwitcher } from '@mymoid/ui-components'
import logoSrc from '@mymoid/ui-components/logo.svg'
import styles from '@/styles/Home.module.css'

const inter = Open_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>nextjs-starter/basic</p>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src={logoSrc}
            alt="MYMOID Logo"
            width={333}
            height={53}
            priority
          />
          <h2 className={[inter.className, styles.slogan].join(' ')}>
            Let’s change the payment landscape together
          </h2>
          <div>
            <ModeSwitcher variant="outlined" color="inherit" />
          </div>
        </div>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>
      </main>
    </>
  )
}
