'use client'
import Head from 'next/head'
import Link from 'next/link'
import {
  ModeSwitcher,
  Button,
  Card,
  CardActions,
  CircularProgress
} from '@mymoid/ui-components'
import { useUser } from '@auth0/nextjs-auth0/client'
import { ERoutes } from '@/utils/constants'

export default function Home() {
  const { user, isLoading } = useUser()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModeSwitcher variant="outlined" color="inherit" />
      <Card>
        {isLoading ? (
          <CircularProgress />
        ) : (
          <CardActions>
            {user ? (
              <>
                <Link href={ERoutes.DASHBOARD}>
                  <Button variant="outlined">Go to Dashboard</Button>
                </Link>
                <Link href={ERoutes.LOGOUT_URL}>
                  <Button>Logout</Button>
                </Link>
              </>
            ) : (
              <>
                <Link href={ERoutes.LOGIN_URL}>
                  <Button variant="contained">Login</Button>
                </Link>
                <Link href={ERoutes.SIGNUP_URL}>
                  <Button variant="outlined">Signup</Button>
                </Link>
              </>
            )}
          </CardActions>
        )}
      </Card>
    </>
  )
}
